# Generated by Django 4.2 on 2024-03-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_cart'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('cart', 'product')},
        ),
    ]
