# Generated by Django 4.2 on 2024-03-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_orderid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
