# Generated by Django 4.2 on 2024-03-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
