# Generated by Django 4.2 on 2024-03-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
